# zexi 0.4.0
config-service_PutConfigRule:
  languages:
    SAP ABAP:
      versions:
        - sdk_version: 1
          github: sap-abap/services/cfs
          excerpts:
            - description:
              snippet_tags:
                - cfs.abapv1.put_config_rule
    Python:
      versions:
        - sdk_version: 3
          github: python/example_code/config
          sdkguide:
          excerpts:
            - description:
              snippet_tags:
                - python.example_code.config-service.ConfigWrapper
                - python.example_code.config-service.PutConfigRule
  services:
    config-service: {PutConfigRule}
config-service_DescribeConfigRules:
  languages:
    SAP ABAP:
      versions:
        - sdk_version: 1
          github: sap-abap/services/cfs
          excerpts:
            - description:
              snippet_tags:
                - cfs.abapv1.describe_config_rule
    Python:
      versions:
        - sdk_version: 3
          github: python/example_code/config
          sdkguide:
          excerpts:
            - description:
              snippet_tags:
                - python.example_code.config-service.ConfigWrapper
                - python.example_code.config-service.DescribeConfigRules
  services:
    config-service: {DescribeConfigRules}
config-service_DeleteConfigRule:
  languages:
    SAP ABAP:
      versions:
        - sdk_version: 1
          github: sap-abap/services/cfs
          excerpts:
            - description:
              snippet_tags:
                - cfs.abapv1.delete_config_rule
    Python:
      versions:
        - sdk_version: 3
          github: python/example_code/config
          sdkguide:
          excerpts:
            - description:
              snippet_tags:
                - python.example_code.config-service.ConfigWrapper
                - python.example_code.config-service.DeleteConfigRule
  services:
    config-service: {DeleteConfigRule}
