# zexi 0.4.0
# The sort key of a service is the short display name (the expanded version of the short entity) without the AWS/Amazon prefix.
acm:
  long: "&ACMlong;"
  short: "&ACM;"
  sort: "ACM"
  version: acm-2015-12-08
api-gateway:
  long: "&ABPlong;"
  short: "&ABP;"
  sort: "API Gateway"
  version: apigateway-2015-07-09
apigatewaymanagementapi:
  long: "&ABPMAlong;"
  short: "&ABPMA;"
  sort: "API Gateway Management"
  version: apigatewaymanagementapi-2018-11-29
application-autoscaling:
  long: "&APP-ASlong;"
  short: "&APP-AS;"
  sort: "Application Auto Scaling"
  version: application-autoscaling-2016-02-06
auditmanager:
  long: "&AMlong;"
  short: "&AM;"
  sort: Audit Manager
  version: auditmanager-2017-07-25
auto-scaling:
  long: "&ASlong;"
  short: "&AS;"
  sort: "EC2 Auto Scaling"
  version: autoscaling-2011-01-01
batch:
  long: "&BATCHlong;"
  short: "&BATCH;"
  sort: "Batch"
  version: batch-2016-08-10
cloudformation:
  long: "&CFNlong;"
  short: "&CFN;"
  sort: "CloudFormation"
  version: cloudformation-2010-05-15
cloudfront:
  long: "&CFlong;"
  short: "&CF;"
  sort: "CloudFront"
  version: cloudfront-2020-05-31
cloudwatch:
  long: "&CWlong;"
  short: "&CW;"
  sort: "CloudWatch"
  version: monitoring-2010-08-01
cloudwatch-events:
  long: "&CWElong;"
  short: "&CWE;"
  sort: "CloudWatch Events"
  version: eventbridge-2015-10-07
cloudwatch-logs:
  long: "&CWLlong;"
  short: "&CWL;"
  sort: "CloudWatch Logs"
  version: logs-2014-03-28
cognito-identity:
  long: "&COGID;"
  short: "&COGID;"
  sort: "Cognito Identity"
  version: cognito-identity-2014-06-30
cognito-identity-provider:
  long: "&COGIDP;"
  short: "&COGIDP;"
  sort: "Cognito Identity Provider"
  version: cognito-idp-2016-04-18
cognito-sync:
  long: "&COGSYNClong;"
  short: "&COGSYNC;"
  sort: "Cognito Sync"
  version: cognito-sync-2014-06-30
comprehend:
  long: "&CMPlong;"
  short: "&CMP;"
  sort: "Comprehend"
  version: comprehend-2017-11-27
config-service:
  long: "&CClong;"
  short: "&CC;"
  sort: "Config"
  version: config-2014-11-12
device-farm:
  long: "&ATPlong;"
  short: "&ATP;"
  sort: "Device Farm"
  version: devicefarm-2015-06-23
dynamodb:
  long: "&DDBlong;"
  short: "&DDB;"
  sort: "DynamoDB"
  version: dynamodb-2012-08-10
ebs:
  long: "&EBSlong;"
  short: "&EBS;"
  sort: "EBS"
  version: ebs-2019-11-02
ec2:
  long: "&EC2long;"
  short: "&EC2;"
  sort: "EC2"
  version: ec2-2016-11-15
ecr:
  long: "&ECRlong;"
  short: "&ECR;"
  sort: "ECR"
  version: ecr-2015-09-21
ecs:
  long: "&ECSlong;"
  short: "&ECS;"
  sort: "ECS"
  version: ecs-2014-11-13
eks:
  long: "&EKSlong;"
  short: "&EKS;"
  sort: "EKS"
  version: eks-2017-11-01
emr:
  long: "&EMRlong;"
  short: "&EMR;"
  sort: "EMR"
  version: elasticmapreduce-2009-03-31
eventbridge:
  long: "&EVlong;"
  short: "&EV;"
  sort: "EventBridge"
  version: eventbridge-2015-10-07
glacier:
  long: "&GLlong;"
  short: "&GLshort;"
  sort: "S3 Glacier"
  version: glacier-2012-06-01
glue:
  long: "&GLUlong;"
  short: "&GLU;"
  sort: "Glue"
  version: glue-2017-03-31
iam:
  long: "&IAMlong;"
  short: "&IAM;"
  sort: "IAM"
  version: iam-2010-05-08
  bundle: iam
iot:
  long: "&IoTlong;"
  short: "&IoT;"
  sort: "IOT"
  version: iot-2015-05-28
kinesis:
  long: "&AKlong;"
  short: "&AK;"
  sort: "Kinesis"
  version: kinesis-2013-12-02
kinesis-analytics-v2:
  long: "&AKAlong;"
  short: "&AKA;"
  sort: "Kinesis DataAnalytics"
  version: kinesisanalyticsv2-2018-05-23
kms:
  long: "&KMSlong;"
  short: "&KMS;"
  sort: "KMS"
  version: kms-2014-11-01
lambda:
  long: "&LAMlong;"
  short: "&LAM;"
  sort: "Lambda"
  version: lambda-2015-03-31
lex:
  long: "&LEX2long;"
  short: "&LEX2;"
  sort: "Lex"
  version: runtime.lex.v2-2020-08-07
lookoutvision:
  long: "&LYRAlong;"
  short: "&LYRA;"
  sort: "Lookout for Vision"
  version: lookoutvision-2020-11-20
medialive:
  long: "&EMLlong;"
  short: "&EML;"
  sort: "MediaLive"
  version: medialive-2017-10-14
mediapackage:
  long: "&EMPlong;"
  short: "&EMP;"
  sort: "MediaPackage"
  version: mediapackage-2017-10-12
organizations:
  long: "&AOlong;"
  short: "&AO;"
  sort: "Organizations"
  version: organizations-2016-11-28
pinpoint:
  long: "&PINlong;"
  short: "&PIN;"
  sort: "Pinpoint"
  version: pinpoint-2016-12-01
  bundle: pinpoint
pinpoint-email:
  long: "&PIN-Email-API;"
  short: "&PIN-Email-API;"
  sort: "Pinpoint Email"
  version: pinpoint-email-2018-07-26
pinpoint-sms-voice:
  long: "&PIN-SMS-Voice-API;"
  short: "&PIN-SMS-Voice-API;"
  sort: "Pinpoint SMS and Voice"
  version: pinpoint-sms-voice-2018-09-05
  bundle: pinpoint
polly:
  long: "&POLlong;"
  short: "&POL;"
  sort: "Polly"
  version: polly-2016-06-10
qldb:
  long: "&QLDBlong;"
  short: "&QLDB;"
  sort: "QLDB"
  version: qldb-2019-01-02
rds:
  long: "&RDSlong;"
  short: "&RDS;"
  sort: "RDS"
  version: rds-2014-10-31
rds-data:
  long: "&RDSDataServicelong;"
  short: "&RDSDataService;"
  sort: "RDS Data Service"
  version: rds-data-2018-08-01
rekognition:
  long: "&REKlong;"
  short: "&REK;"
  sort: "Rekognition"
  version: rekognition-2016-06-27
  caveat: The code examples in this chapter are intended to supplement the
    code examples found throughout the rest of this guide.
route-53:
  long: "&R53long;"
  short: "&R53;"
  sort: "Route 53"
  version: route53-2013-04-01
route53-recovery-cluster:
  long: "&R53ARClong;"
  short: "&R53ARC;"
  sort: "Application Recovery Controller"
  version: route53-recovery-cluster-2019-12-02
s3:
  long: "&S3long;"
  short: "&S3;"
  sort: "S3"
  version: s3-2006-03-01
sagemaker:
  long: "&SMlong;"
  short: "&SM;"
  sort: "SageMaker"
  version: sagemaker-2017-07-24
secrets-manager:
  long: "&ASMlong;"
  short: "&ASM;"
  sort: "Secrets Manager"
  version: secretsmanager-2017-10-17
ses:
  long: "&SESlong;"
  short: "&SES;"
  sort: "SES"
  version: email-2010-12-01
  bundle: ses
sesv2:
  long: "&SESv2long;"
  short: "&SESv2;"
  sort: "SES v2 API"
  version: sesv2-2019-09-27
  bundle: ses
sfn:
  long: "&SFNlong;"
  short: "&SFN;"
  sort: "Step Functions"
  version: states-2016-11-23
snowball:
  long: "&Frozenlong;"
  short: "&Frozen;"
  sort: "Snowball"
  version: snowball-2016-06-30
sns:
  long: "&SNSlong;"
  short: "&SNS;"
  sort: "SNS"
  version: sns-2010-03-31
sqs:
  long: "&SQSlong;"
  short: "&SQS;"
  sort: "SQS"
  version: sqs-2012-11-05
sts:
  long: "&STSlong;"
  short: "&STS;"
  sort: "STS"
  version: sts-2011-06-15
  bundle: iam
ssm:
  long: "&SYSlong;"
  short: "&SYS;"
  sort: "Systems Manager"
  version: ssm-2014-11-06
textract:
  long: "&TEXTRACTlong;"
  short: "&TEXTRACT;"
  sort: "Textract"
  version: textract-2018-06-27
transcribe:
  long: "&TSClong;"
  short: "&TSC;"
  sort: "Transcribe"
  version: transcribe-2017-10-26
transcribe-medical:
  long: "&TSClong;"
  short: "&TSC;"
  sort: "Transcribe medical"
  version: transcribe-2017-10-26
translate:
  long: "&TSLlong;"
  short: "&TSL;"
  sort: "Translate"
  version: translate-2017-07-01
