[package]
name = "ec2-code-examples"
version = "0.1.0"
authors = [
  "Russell Cohen <rcoh@amazon.com>",
  "Doug Schwartz <dougsch@amazon.com>",
]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[dependencies]
aws-config = { version = "1.0.1", features = ["behavior-version-latest"] }
aws-sdk-ec2 = { version = "1.3.0" }
aws-types = { version = "1.0.1" }
tokio = { version = "1.20.1", features = ["full"] }
clap = { version = "4.4", features = ["derive"] }
tracing-subscriber = { version = "0.3.17", features = ["env-filter"] }
tracing = "0.1.40"
aws-smithy-runtime-api = "1.6.2"
mockall = "0.13.0"
inquire = "0.7.5"
reqwest = "0.12.5"
aws-sdk-ssm = "1.40.0"
aws-smithy-async = "1.2.1"
