[package]
name = "textract-code-examples"
version = "0.1.0"
authors = [
    "Zelda Hessler <zhessler@amazon.com>",
]
edition = "2021"

# For more keys and their definitions, see https://doc.rust-lang.org/cargo/reference/manifest.html.

[dependencies]
aws-config = { git = "https://github.com/awslabs/aws-sdk-rust", branch = "next" }
aws-sdk-textract = { git = "https://github.com/awslabs/aws-sdk-rust", branch = "next" }
tokio = { version = "1.27", features = ["full"] }
structopt = { version = "0.3", default-features = false }
tracing-subscriber = { version = "0.3.15", features = ["env-filter"] }
thiserror = "1.0.49"
aws-types = "0.56.1"
