[package]
name = "testing-examples"
version = "0.1.0"
authors = [
  "John Disanti <jdisanti@amazon.com>",
  "Doug Schwartz <dougsch@amazon.com>",
]
edition = "2018"

# snippet-start:[testing.rust.Cargo.toml]
[dependencies]
async-trait = "0.1.51"
# snippet-end:[testing.rust.Cargo.toml]
aws-config = { git = "https://github.com/awslabs/aws-sdk-rust", branch = "main" }
aws-sdk-s3 = { git = "https://github.com/awslabs/aws-sdk-rust", branch = "main" }
aws-smithy-client = { git = "https://github.com/awslabs/aws-sdk-rust", branch = "main", features = [
  "test-util",
] }
tokio = { version = "1.20.1", features = ["full"] }
serde_json = "1"
structopt = { version = "0.3", default-features = false }
tracing-subscriber = { version = "0.3.15", features = ["env-filter"] }

[[bin]]
name = "intro"
path = "src/intro.rs"
