[package]
name = "telephone-code-example"
version = "0.1.0"
authors = ["Doug Schwartz <dougsch@amazon.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aws-config = "0.3.0"
aws-sdk-polly = "0.3.0"
aws-sdk-s3 = "0.3.0"
aws-sdk-transcribe = "0.3.0"
tokio = { version = "1", features = ["full"] }
async-stream = "0.3"
bytes = "1"
http = "0.1.1"
reqwest = "0.11.4"
serde_json = "1.0"
structopt = { version = "0.3", default-features = false }
tracing-subscriber = { version = "0.3.5", features = ["env-filter"] }
