[package]
name = "kms-helloworld"
version = "0.1.0"
authors = ["Russell Cohen <rcoh@amazon.com>"]
edition = "2018"
description = "Example usage of the KMS service"

[dependencies]
kms = { package = "aws-sdk-kms", path = "../../build/aws-sdk/kms" }
aws-hyper = { path = "../../build/aws-sdk/aws-hyper" }
tokio = { version = "1", features = ["full"]}
# optional
env_logger = "0.8.2"
tracing-subscriber = { version = "0.2.16", features = ["fmt"] }
