[package]
name = "s3-code-examples"
version = "0.1.0"
authors = ["Russell Cohen <rcoh@amazon.com>", "Doug Schwartz <dougsch@amazon.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aws-config = "0.6.0"
# snippet-start:[s3.rust.s3-object-lambda-cargo.toml]
aws-endpoint = "0.6.0"
# snippet-end:[s3.rust.s3-object-lambda-cargo.toml]
aws-sdk-s3 = "0.6.0"
tokio = { version = "1", features = ["full"] }
structopt = { version = "0.3", default-features = false }
tracing-subscriber = { version = "0.3.5", features = ["env-filter"] }
uuid = { version = "0.8", features = ["serde", "v4"] }