[package]
name = "s3_code_examples"
version = "0.1.0"
authors = [
  "Russell Cohen <rcoh@amazon.com>",
  "Doug Schwartz <dougsch@amazon.com>",
]
edition = "2021"

[lib]
name = "s3_service"
path = "src/s3-service-lib.rs"

[[bin]]
name = "s3_getting_started"
path = "src/bin/s3-getting-started.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dev-dependencies]
assert_cmd = "2.0"
predicates = "2.1"

[dependencies]
aws-config = { git = "https://github.com/awslabs/aws-sdk-rust", branch = "main" }
# snippet-start:[s3.rust.s3-object-lambda-cargo.toml]
aws-endpoint = { git = "https://github.com/awslabs/aws-sdk-rust", branch = "main" }
# snippet-end:[s3.rust.s3-object-lambda-cargo.toml]
aws-sdk-s3 = { git = "https://github.com/awslabs/aws-sdk-rust", branch = "main" }
aws-smithy-http = { git = "https://github.com/awslabs/aws-sdk-rust", branch = "main", features = ["rt-tokio"] }
aws-smithy-types = { git = "https://github.com/awslabs/aws-sdk-rust", branch = "main" }
bytes = "0.4.12"
futures-util = { version = "0.3.21", features = ["alloc"] }
http = "0.2.8"
http-body = "0.4.5"
md-5 = "0.10.1"
rand = "0.5.0"
structopt = { version = "0.3", default-features = false }
thiserror = "1.0"
tokio = { version = "1.20.1", features = ["full"] }
tokio-stream = "0.1.8"
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.5", features = ["env-filter"] }
uuid = { version = "0.8", features = ["serde", "v4"] }
