# Note: this workspace exists solely for the convenience of 
# compiling/auto-formatting/testing all the AWS Rust SDK examples together.
[workspace]
resolver = "2"
members = [
    "detect_faces",
    "detect_labels",
    "photo_asset_management",
    "rest_ses",
    "telephone"
]

[profile.release.package.photo_asset_management]
opt-level = 3
strip = "debuginfo"
