[package]
name = "tls"
version = "0.1.0"
edition = "2018"

[[bin]]
name = "tls"
path = "src/main.rs"

[lib]
name = "tls"
path = "src/lib.rs"

[dependencies]
aws-config = { git = "https://github.com/awslabs/aws-sdk-rust", branch = "main" }
aws-smithy-client = { git = "https://github.com/awslabs/aws-sdk-rust", branch = "main" }
aws-sdk-kms = { git = "https://github.com/awslabs/aws-sdk-rust", branch = "main", default-features = false }
webpki-roots = "0.22.4"
tokio = { version = "1.20.1", features = ["full"] }
rustls = "0.20.6"
hyper-rustls = { version = "0.23.0", features = ["http2"] }
