[package]
name = "secretsmanager-helloworld"
version = "0.1.0"
authors = ["AWS Rust SDK Team <aws-sdk-rust@amazon.com>", "Nas Taibi <naceredd@amazon.com>"]
edition = "2018"
description = "Example usage of the SecretManager service"

[dependencies]
secretsmanager = { package = "aws-sdk-secretsmanager", path = "../../build/aws-sdk/secretsmanager" }
aws-hyper = { path = "../../build/aws-sdk/aws-hyper" }
tokio = { version = "1", features = ["full"]}
# optional
tracing-subscriber = { version = "0.2.16", features = ["fmt"] }
