[package]
name = "bedrock-runtime"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aws-config = "1.5.4"
aws-sdk-bedrockruntime = "1.40.0"
tokio = { version = "1.38.1", features = ["full"] }
tracing-subscriber = "0.3.18"
