[package]
name = "example-lambda-calculator"
version = "0.1.0"
authors = [
  "David Souther <dpsouth@amazon.com>",
]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aws-config = { version = "1.0.1" }
aws-sdk-ec2 = { version = "1.3.0" }
aws-sdk-lambda = { version = "1.3.0" }
aws-sdk-s3 = { version = "1.4.0" }
lambda_runtime = "0.8.0"
clap = { version = "~4.4", features = ["derive"] }
tokio = { version = "1.20.1", features = ["full"] }
tracing-subscriber = { version = "0.3.15", features = ["env-filter", "json"] }
time = "0.3"
tracing = "0.1.37"
serde_json = "1.0.94"
anyhow = "1.0.71"
serde = "1.0.164"

