[package]
name = "iam-code-examples"
version = "0.1.0"
authors = ["Russell Cohen <rcoh@amazon.com>", "Doug Schwartz <dougsch@amazon.com"]
edition = "2018"
description = "Example usage of the IAM service"

[dependencies]
aws-config = "0.3.0"
aws-sdk-iam = "0.3.0"
aws-hyper = "0.3.0"
tokio = { version = "1", features = ["full"]}
serde_json = "1"
structopt = { version = "0.3", default-features = false }
tracing-subscriber = "0.2.18"
