[package]
name = "iam-code-examples"
version = "0.1.0"
authors = [
  "Russell Cohen <rcoh@amazon.com>",
  "Doug Schwartz <dougsch@amazon.com",
]
edition = "2021"
description = "Example usage of the IAM service"

[lib]
name = "iam_service"
path = "src/iam-service-lib.rs"

[[bin]]
name = "iam_getting_started"
path = "src/bin/iam-getting-started.rs"

[dependencies]
aws-config = { git = "https://github.com/awslabs/aws-sdk-rust", branch = "main" }
aws-credential-types = { git = "https://github.com/awslabs/aws-sdk-rust", branch = "main", features = ["hardcoded-credentials"] }
aws-hyper = { git = "https://github.com/awslabs/aws-sdk-rust", branch = "main" }
aws-sdk-iam = { git = "https://github.com/awslabs/aws-sdk-rust", branch = "main" }
aws-sdk-s3 = { git = "https://github.com/awslabs/aws-sdk-rust", branch = "main" }
aws-sdk-sts = { git = "https://github.com/awslabs/aws-sdk-rust", branch = "main" }
aws-smithy-client = { git = "https://github.com/awslabs/aws-sdk-rust", branch = "main", features = ["test-util"] }
aws-smithy-http = { git = "https://github.com/awslabs/aws-sdk-rust", branch = "main" }
aws-types = { git = "https://github.com/awslabs/aws-sdk-rust", branch = "main" }
sdk-examples-test-utils = { path = "../test-utils" }
tokio = { version = "1.20.1", features = ["full"] }
clap = { version = "4.2.1", features = ["derive"] }
tracing-subscriber = { version = "0.3.15", features = ["env-filter"] }
uuid = { version = "0.8", features = ["serde", "v4"] }
tower-service = "0.3.2"
http = "0.2.8"
futures = "0.3.28"
async_once = "0.2.6"
lazy_static = "1.4.0"
