[package]
name = "photo_asset_management"
version = "0.1.0"
edition = "2021"

[package.metadata.lambda.env]
RUST_LOG = "info,pam=trace,aws_smithy_http=trace"
AWS_REGION = "us-west-2"
LABELS_TABLE_NAME	= "FROM_CDK"
NOTIFICATION_TOPIC = "FROM_CDK"
STORAGE_BUCKET_NAME = "FROM_CDK"
WORKING_BUCKET_NAME = "FROM_CDK"
_HANDLER = "labels"

[dependencies]
anyhow = "1.0.70"
aws-config = { git = "https://github.com/awslabs/aws-sdk-rust", branch = "next" }
aws-sdk-dynamodb = { git = "https://github.com/awslabs/aws-sdk-rust", branch = "next" }
aws-sdk-rekognition = { git = "https://github.com/awslabs/aws-sdk-rust", branch = "next" }
aws-sdk-s3 = { git = "https://github.com/awslabs/aws-sdk-rust", branch = "next" }
aws-sdk-sns = { git = "https://github.com/awslabs/aws-sdk-rust", branch = "next" }
aws-smithy-http = { git = "https://github.com/awslabs/aws-sdk-rust", branch = "next" }
aws-smithy-runtime = { git = "https://github.com/awslabs/aws-sdk-rust", branch = "next" }
aws-smithy-types-convert ={ git = "https://github.com/awslabs/aws-sdk-rust", branch = "next", features = ["convert-chrono"] }
aws_lambda_events = { version = "0.11.1", features = ["s3", "apigw"], default-features = false }
bytes = "1.4.0"
chrono = "0.4.24"
crossbeam-channel = "0.5.8"
futures = "0.3.28"
http = "0.2.9"
lambda_http = "0.8.0"
lambda_runtime = "0.8.0"
miniz_oxide = "0.7.1"
pin-project = "1.0.12"
pipe = "0.4.0"
sdk-examples-test-utils = { path = "../../test-utils" }
serde = { version = "1.0.159", features = ["derive"] }
serde_json = "1.0.95"
streaming-zip = "0.5.0"
tempfile = "3.5.0"
tokio = { version = "1.27.0", features = ["macros"] }
tokio-stream = "0.1.12"
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.16", features = ["env-filter"] }
uuid = { version = "1.3.1", features = ["v4"] }
zip_next = { version = "0.10.2", default-features=false, features = ["chrono", "deflate"] }
