[package]
name = "setting-timeouts"
version = "0.1.0"
authors = ["Zelda Hessler zhessler@amazon.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aws-config = { git = "https://github.com/awslabs/aws-sdk-rust", branch = "main" }
aws-sdk-s3 = { git = "https://github.com/awslabs/aws-sdk-rust", branch = "main" }
aws-smithy-client = { git = "https://github.com/awslabs/aws-sdk-rust", branch = "main", features = [
  "rustls",
] }
aws-smithy-types = { git = "https://github.com/awslabs/aws-sdk-rust", branch = "main" }
tokio = { version = "1", features = ["full"] }
tracing-subscriber = { version = "0.3.15", features = ["env-filter"] }
