[package]
name = "dynamodb-code-examples"
version = "0.1.0"
authors = ["Russell Cohen <rcoh@amazon.com>", "Doug Schwartz <dougsch@amazon.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aws-config = "0.2.0"
aws-sdk-dynamodb = "0.2.0"
aws-hyper = "0.2.0"
aws-http = "0.2.0"
aws-smithy-http = "0.32.0"
aws-smithy-types = "0.32.0"
http = "0.2.5"
rand = "0.8.3"
structopt = { version = "0.3", default-features = false }
tokio = { version = "1", features = ["full"] }
serde_json = "1"
tracing-subscriber = { version = "0.2.16", features = ["fmt"] }
