[package]
name = "dynamodb-code-examples"
version = "0.1.0"
authors = ["Russell Cohen <rcoh@amazon.com>", "Doug Schwartz <dougsch@amazon.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aws-config = "0.4.1"
aws-sdk-dynamodb = "0.4.1"
aws-http = "0.4.1"
aws-smithy-client = { version = "0.34.1", features = ["client-hyper", "rustls", "rt-tokio"] }
aws-smithy-http = { version = "0.34.1", features = ["rt-tokio"] }
aws-smithy-types = "0.34.1"
http = "0.2.5"
rand = "0.8.3"
serde_json = "1"
structopt = { version = "0.3", default-features = false }
tokio = { version = "1", features = ["full"] }
#tokio-stream = "0.1.8"
tracing-subscriber = { version = "0.3.5", features = ["env-filter"] }
