[package]
name = "qldb-code-examples"
version = "0.1.0"
authors = [
  "Russell Cohen <rcoh@amazon.com>",
  "Doug Schwartz <dougsch@amazon.com>",
]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aws-config = { git = "https://github.com/awslabs/aws-sdk-rust", branch = "next" }
aws-sdk-qldb = { git = "https://github.com/awslabs/aws-sdk-rust", branch = "next" }
aws-sdk-qldbsession = { git = "https://github.com/awslabs/aws-sdk-rust", branch = "next" }
tokio = { version = "1.20.1", features = ["full"] }
tokio-stream = { version = "0.1.9", features = ["default"] }
clap = { version = "~4.4", features = ["derive"] }
tracing-subscriber = { version = "0.3.15", features = ["env-filter"] }
