[package]
name = "rest_ses"
version = "0.1.0"
edition = "2021"


[lib]
path = "src/lib.rs"

[[bin]]
path = "src/main.rs"
name = "rest_ses"

[dependencies]
actix-web = "4"
aws-config = { git = "https://github.com/awslabs/aws-sdk-rust", branch = "main" }
aws-sdk-rdsdata = { git = "https://github.com/awslabs/aws-sdk-rust", branch = "main" }
chrono = { version = "0.4.22", default-features = false, features = ["clock", "serde"] }
config = "0.13.2"
once_cell = "1.15.0"
reqwest = "0.11.12"
secrecy = { version = "0.8.0", features = ["serde"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1.0.86"
tokio = {version = "1", features = ["macros", "rt-multi-thread"]}
tracing = "0.1.37"
tracing-actix-web = "0.6.1"
tracing-bunyan-formatter = "0.3.4"
tracing-log = "0.1.3"
tracing-subscriber = { version = "0.3", features = ["registry", "env-filter"] }
uuid = { version = "1.2.1", features = ["v4", "serde"] }
