[package]
name = "using_native_tls_instead_of_rustls"
version = "0.1.0"
authors = ["Zelda Hessler zhessler@amazon.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# aws-config pulls in rustls and several other things by default. We have to disable defaults in order to use native-tls
# and then manually bring the other defaults back
aws-config = { version = "0.3.0", default-features = false, features = ["native-tls", "rt-tokio"] }
# aws-sdk-s3 brings in rustls by default so we disable that in order to use native-tls only
aws-sdk-s3 = { version = "0.3.0", default-features = false, features = ["native-tls"] }
# aws-sdk-sts is the same as aws-sdk-s3
aws-sdk-sts = { version = "0.3.0", default-features = false, features = ["native-tls"] }
tokio = { version = "1", features = ["full"] }
tracing-subscriber = { version = "0.3.5", features = ["env-filter"] }
