[package]
name = "using-native-tls-instead-of-rustls"
version = "0.1.0"
authors = ["Zelda Hessler zhessler@amazon.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# aws-config pulls in rustls and several other things by default. We have to disable defaults in order to use native-tls
# and then manually bring the other defaults back
aws-config = { git = "https://github.com/awslabs/aws-sdk-rust", branch = "next", default-features = false, features = [
  "native-tls",
  "rt-tokio",
] }
# aws-sdk-s3 brings in rustls by default so we disable that in order to use native-tls only
aws-sdk-s3 = { git = "https://github.com/awslabs/aws-sdk-rust", branch = "next", default-features = false, features = [
  "native-tls",
] }
# aws-sdk-sts is the same as aws-sdk-s3
aws-sdk-sts = { git = "https://github.com/awslabs/aws-sdk-rust", branch = "next", default-features = false, features = [
  "native-tls",
] }
tokio = { version = "1.20.1", features = ["full"] }
tracing-subscriber = { version = "0.3.15", features = ["env-filter"] }
