[package]
name = "lambda-code-examples"
version = "0.1.0"
authors = [
  "Richard H. Boyd <rhboyd@amazon.com>",
  "Doug Schwartz <dougsch@amazon.com>",
]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aws-config = { git = "https://github.com/awslabs/aws-sdk-rust", branch = "main" }
aws-sdk-ec2 = { git = "https://github.com/awslabs/aws-sdk-rust", branch = "main" }
aws-sdk-lambda = { git = "https://github.com/awslabs/aws-sdk-rust", branch = "main" }
aws-sdk-s3 = { git = "https://github.com/awslabs/aws-sdk-rust", branch = "main" }
env_logger = "0.9.0"
lambda_runtime = "0.4"
log = "0.4"
serde = { version = "1", features = ["derive"] }
structopt = { version = "0.3", default-features = false }
tokio = { version = "1.20.1", features = ["full"] }
tracing-subscriber = { version = "0.3.15", features = ["env-filter"] }
time = "0.3"
