# snippet-start:[localstack.rust.use-localstack-cargo.toml]
[package]
name = "localstack-example"
version = "0.1.0"
authors = ["Doug Schwartz <dougsch@amazon.com>"]
edition = "2018"

[dependencies]
aws-config = "0.4.1"
aws-sdk-s3 = "0.4.1"
aws-sdk-sqs = "0.4.1"
aws-types = "0.4.1"
aws-smithy-http = "0.34.1"
tokio = { version = "1", features = ["full"] }
http = "0.2"
tracing-subscriber = { version = "0.3.5", features = ["env-filter"] }
# snippet-end:[localstack.rust.use-localstack-cargo.toml]
