name: Lint Code Base
on:
  push:
    branches: [ main ]
    paths: cloudformation/**/** # run linter when files are committed to the cfn directory
  pull_request:
    branches: [ main ]
    paths: cloudformation/**/**

jobs:
  build:
    name: Lint Code Base
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          # Full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0

        # documentation: https://github.com/github/super-linter#example-connecting-github-action-workflow
      - name: Super-Linter
        uses: github/super-linter@v3.14.0
        env:
          VALIDATE_CLOUDFORMATION: true # conditions to lint cfn templates
          VALIDATE_ALL_CODEBASE: false # only new or edited files are parsed
          FILTER_REGEX_INCLUDE: .*cloudformation/.*/.*.* # lint in cfn directory
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # action needed by GitHub
