name: cpp lint check
on:
  push:
    paths:
      - 'cpp/**'
    branches:
      - main
  pull_request:
    paths:
      - 'cpp/**'
  workflow_dispatch:
permissions:
  contents: read
  pull-requests: write
jobs:
  cpplint:
    name: cpp lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run clang-tidy check
        uses: ./.github/cpp-linter
        with:
          config_file: ./.github/cpp-linter/clang-tidy-config.txt
          token: ${{ secrets.GITHUB_TOKEN }}
