name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      
      - name: Log in to Docker Hub
        uses: docker/login-action@master
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@master
        with:
          images: fordataws/aws-sdk-code-examples
      
      - name: Build and push Docker image - Ruby
        uses: docker/build-push-action@master
        with:
          context: ruby
          push: true
          tags: fordataws/ruby:latest
          labels: ${{ steps.meta.outputs.labels }}
          
      - name: Build and push Docker image - Python
        uses: docker/build-push-action@master
        with:
          context: python
          push: true
          tags: fordataws/python:latest
          labels: ${{ steps.meta.outputs.labels }}
    
      - name: Build and push Docker image - JavaScriptv3
        uses: docker/build-push-action@master
        with:
          context: javascriptv3
          push: true
          tags: fordataws/javascriptv3:latest
          labels: ${{ steps.meta.outputs.labels }}
      
      - name: Build and push Docker image - gov2
        uses: docker/build-push-action@master
        with:
          context: gov2
          push: true
          tags: fordataws/gov2:latest
          labels: ${{ steps.meta.outputs.labels }}
      
      - name: Build and push Docker image - dotnetv3
        uses: docker/build-push-action@master
        with:
          context: dotnetv3
          push: true
          tags: fordataws/dotnetv3:latest
          labels: ${{ steps.meta.outputs.labels }}
