name: Dotnet lint check
on:
  pull_request:
  workflow_dispatch:
permissions:
  contents: read
jobs:
  dotnetcheck:
    name: Lint DotNet
    runs-on: ubuntu-latest
    steps:
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: |
            5.0.x
            6.0.x
      - name: Checkout files
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            .github
            dotnetv3
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v41
        with:
          files: "dotnetv3/**/*.{cs,sln,csproj,json}"
      - name: Build check
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          cd dotnetv3
          dotnet build -v=q --property WarningLevel=0 /clp:ErrorsOnly
      - name: Lint and format check
        if: steps.changed-files.outputs.any_changed == 'true' && (success() || failure())
        run: |
          cd dotnetv3
          dotnet format --verify-no-changes
