name: golangci-lint
on:
  push:
    paths:
      - 'gov2/**'
    branches:
      - main
  pull_request:
    paths:
      - 'gov2/**'
  workflow_dispatch:
permissions:
  contents: read
  # Optional: Allow read access to pull request. Use with `only-new-issues` option.
  # pull-requests: read
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'
      - name: install golangci-lint
        run: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.47.3
#        uses: golangci/golangci-lint-action@v3
#        with:
#          # Optional: Version of golangci-lint to use. For example, v1.2 or v1.2.3, or latest to use the latest version.
#          version: latest
#
#          # The following causes golangci-init to do nothing, so all it does is
#          # install golang and golangci.
#          args: --version
#
#          # Optional: golangci-lint command line arguments.
#          # args: --issues-exit-code=0
#
#          # Optional: Show only new issues if it's a pull request. The default value is `false`.
#          # only-new-issues: true
#
#          # Optional: If set to true, all caching functionality is completely disabled.
#          #           Takes precedence over all other caching options.
#          # skip-cache: true
#
#          # Optional: If set to true, the action doesn't cache or restore ~/go/pkg.
#          # skip-pkg-cache: true
#
#          # Optional: If set to true, the action doesn't cache or restore ~/.cache/go-build.
#          # skip-build-cache: true
      - name: run golangci-lint
        run: |
          cd gov2/dynamodb
          golangci-lint run --config ../../.github/linters/.golangci.yml --new
