name: golangci-lint
on:
  pull_request:
  workflow_dispatch:
permissions:
  contents: read
jobs:
  golangci:
    name: Lint GoLang
    runs-on: ubuntu-latest
    steps:
      - name: Checkout files
        uses: actions/checkout@v3
        with:
          sparse-checkout: |
            .github
            gov2
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v41
        with:
          files: "gov2/**/*.go"
      - uses: actions/setup-go@v3
        if: steps.changed-files.outputs.any_changed == 'true'
        with:
          go-version: 1.18
      - name: install golangci-lint
        if: steps.changed-files.outputs.any_changed == 'true'
        run: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.47.3
      - name: run golangci-lint
        if: steps.changed-files.outputs.any_changed == 'true'
          # If you get a linting error of "File is not `goimports`-ed", the solution is to run "gofmt -w ./<folder>".
        run: |
          cd gov2
          ./lint_all_go.sh
