name: JavaScript

on:
  push:
    paths:
      - "javascriptv3/**"
    branches:
      - main
  pull_request:
    paths:
      - "javascriptv3/**"
  workflow_dispatch:

jobs:
  lint:
    name: Lint Javascript
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        name: Checkout files
        with:
          sparse-checkout: |
            javascriptv3
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v41
        with:
          files: "javascriptv3/**/*.{js,ts,jsx,tsx,json}"
      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"
      - run: npm i --prefix javascriptv3
        name: Install dependencies
      - run: |
          changed_files=(${{steps.changed-files.outputs.all_changed_files}})
          npm run --prefix javascriptv3 ci-lint -- ${changed_files[@]//javascriptv3\/}
        name: Lint added and modified files
