name: Rust
on:
  push:
    paths:
      - "rust_dev_preview/**"
    branches:
      - main
  pull_request:
    paths:
      - "rust_dev_preview/**"
  workflow_dispatch:
permissions:
  contents: read
jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: pre-setup
        run: sudo apt-get update && sudo apt-get install -y libclang-dev
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: check
          args: --all-targets --manifest-path rust_dev_preview/Cargo.toml
      - uses: actions-rs/cargo@v1
        if: success() || failure()
        with:
          command: clippy
          args: --manifest-path rust_dev_preview/Cargo.toml -- -D warnings
      - uses: actions-rs/cargo@v1
        if: success() || failure()
        with:
          command: test
          args: --manifest-path rust_dev_preview/Cargo.toml
        env:
          APP_ENVIRONMENT: test
