name: Validate Documentation Metadata

on:  # yamllint disable-line rule:truthy
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  validate-doc-metadata:
    name: Validate Doc Metadata
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo content
        uses: actions/checkout@v4
      - name: validate metadata
        uses: awsdocs/aws-doc-sdk-examples-tools@release/2024-08-28-A
        with:
          doc_gen_only: "False"
          strict_titles: "True"
